### ISSUE TITLE
deploy.js cannot process :then: statement and thus later returns exceeds block gas limit

### ISSUE THREAD

**Issue by ubrals** [HappyFunCorp/Webthereum#1]
Hi. I am enjoying your tutorial, but I am stuck with deploy.js

The default deploy.js does not work. Can you help me, please?

When I run `node`, I get:
$ node deploy.js
/Users/mig/etheretc/webthereum/node/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=n

TypeError: web3.eth.getTransactionCount(...).then is not a function
    at deployContract (/Users/mig/etheretc/webthereum/node/deployDef.js:12:61)
    at Object.<anonymous> (/Users/mig/etheretc/webthereum/node/deployDef.js:8:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3

So I tried to workaround the ".then" statement and then I had many more exceptions and errors.
This is the final version with such error:
"txn err Error: exceeds block gas limit"

deploy.js:
function deployContract() {
    // txnCount = console.log(web3.eth.getTransactionCount(process.env.RINKEBY_ADDRESS));
    txnCount = web3.eth.getTransactionCount(process.env.RINKEBY_ADDRESS);
    console.log(txnCount);
//     web3.eth.getTransactionCount(process.env.RINKEBY_ADDRESS).then((txnCount) => {
//     // txnCount => {
console.log("txn count", txnCount);
const source = fs.readFileSync(__dirname+'/../truffle/contracts/MyPrize.sol');
const compiled = solc.compile(source.toString(), 1);
const bytecode = compiled.contracts[':MyPrize'].bytecode;
const rawContractTx = {
// from: process.env.RINKEBY_ADDRESS, nonce: web3.utils.toHex(txnCount), gasLimit: web3.utils.toHex(4000000), gasPrice: web3.utils.toHex(20000000000), data: '0x' + bytecode,
from: process.env.RINKEBY_ADDRESS, 
// nonce: web3.utils.toHex(txnCount), 
// gasLimit: web3.utils.toHex(4000000), 
// gasPrice: web3.utils.toHex(20000000000), 
nonce: web3.toWei(txnCount, "ether"), 
gasLimit: web3.toWei("4000", "ether"), 
gasPrice: web3.toWei("20000000", "ether"), 
data: '0x' + bytecode,
// web3.utils.toWei("0.001", "ether"),
};
console.log("contract deploying...");
// console.log(rawContractTx);
sendRaw(rawContractTx);
// });
// };
}
function showABI() {
 const source = fs.readFileSync(__dirname+'/../truffle/contracts/MyPrize.sol');
 const compiled = solc.compile(source.toString(), 1);
 const abi = compiled.contracts[':MyPrize'].interface;
 console.log("abi", abi);
}
function sendRaw(rawTx) {
 var privateKey = new Buffer(process.env.RINKEBY_KEY, 'hex');
 var transaction = new tx(rawTx);
 transaction.sign(privateKey);
 var serializedTx = transaction.serialize().toString('hex');
 // web3.eth.sendSignedTransaction(
 web3.eth.sendRawTransaction(
'0x' + serializedTx, function(err, result) {
if(err) {
console.log("txn err", err);
} else {
console.log("txn result", result);
} });
}

**Comment by rezendi** [comment]
Hmm. Regarding the first point, are you certain you've set the RINKEBY_ADDRESS environment variable correctly? If it isn't set, then the getTransactionCount method may return an error rather than a Promise, which would explain the results you're seeing.

It's also possible that the web3 which Node is importing is a different version which doesn't return a Promise for getTransactionCount -- judging from your rewritten code I think a web3 versioning issue is the most likely culprit here, but obviously it's hard to be certain.

As for the second point -- that seems to indicate that the Rinkeby blockchain is rejecting the transaction because deploying it would be too costly. At first glance it seems that this is probably because your line

gasLimit: web3.toWei("4000", "ether"),

sets the gasLimit to four thousand whereas four million would be more appropriate here...? The Rinkeby gas limit is currently 7000000 according to https://www.rinkeby.io/#stats which should be more than ample for this transaction.

**Comment by baroncharlus** [comment]
Running into the first part of @ubrals error myself. running `node deploy.js` returns:
`TypeError: web3.eth.getTransactionCount(...).then is not a function`

That's with npm@5.6.0, web3@0.20.4 (latest version avail. on npm).
It's not the environment variables, either, as the same error appears even with a hardcoded address.

Finally, running the following without `.then` works:

```node
var Web3 = require('web3');
const web3 = new Web3(new Web3.providers.HttpProvider("https://rinkeby.infura.io/"));

web3.eth.getTransactionCount(process.env.RINKEBY_ADDRESS)
```
but it returns 0, when etherscan shows 1 txn.

All that said, thanks for the tutorial. Valueable entry point into this stuff.

**Comment by rezendi** [comment]
Ah -- see if you can install / use web3 1.0.0-beta.27 , per https://github.com/HappyFunCorp/Webthereum/blob/master/node/package-lock.json

I think you have the alpha version of web3, which uses callbacks rather than promises.

Why npm installed different versions on our machines is a mystery known only to them -- when I asked for the latest it gave me the beta.27 ...

(Alternately, of course replace the "then" with just passing the subsequent method as a callback.)

**Comment by rezendi** [comment]
Ah, the latest version of web3 changed two days ago, to a non-beta release which has different method signatures. Sigh. Presumably when they go back to the 1.0 beta branch it will start working again. Will tweak tutorial, but for future reference, replace

npm install web3

with

npm install web3@1.0.0-beta.27

**Comment by baroncharlus** [comment]
That definitely explains it. Works now. Thanks for tracking that down. one of those idiosyncrasies!

As an aside, even passing as a callback gave me trouble with that alpha version. Something funky going on with `utils.toHex`. Upgrading to the beta release fixed that, too.

**Comment by ubrals** [comment]
Thank you for your time, @rezendi . Yes, the environment variable was set. Also used a local variable in another version.
Also, that gas limit was another workaround I tried.
Anyway, I will review the code and software versions based on what you said and also @baroncharlus .
Thank you very much.
